version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    networks:
      - server-net
    restart: "no"

  server:
    build: "./server"
    ports:
      - "8080:8080"
    environment:
      DB_URL: "mongodb://root:pass12345@db:27017"
      DB_HOST: 127.0.0.1
      DB_PORT: 27017
      DB_USERNAME: root
      DB_PASSWORD: pass12345
      PORT: 8080
    restart: "no"
    depends_on:
      - db
    links:
      - "db"
    networks:
      - server-net
  
  client_mobile:
    build: 
      context: "./client"
      dockerfile: Dockerfile.android
    volumes:
      - data:/data/mobile_client

  client_web:
    build: ./client
    ports:
      - "8081:8081"
    volumes:
      - data:/data/client
    depends_on:
      - server
      - client_mobile

volumes:
  data:
networks:
  server-net:
    driver: bridge
  