version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    networks:
      - server-net
    restart: "no"

  server:
    build: "./server"
    ports:
      - "3000:3000"
    environment:
      DB_URL: "mongodb://root:pass12345@db:27017"
      DB_HOST: 127.0.0.1
      DB_PORT: 27017
      DB_USERNAME: root
      DB_PASSWORD: pass12345
      PORT: 3000
    restart: "no"
    depends_on:
      - db
    links:
      - "db"
    networks:
      - server-net
  
  # client_mobile:
  #   build: 
  #     context: "./client"
  #     dockerfile: Dockerfile.android

  client_web:
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - data:/data/www/apk:Z
    depends_on:
      - server

volumes:
  data:
networks:
  server-net:
    driver: bridge
  