/*
 * AREA
 * Area for epitech
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Area);
  }
}(this, function(expect, Area) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Area.AreaApi();
  });

  describe('(package)', function() {
    describe('AreaApi', function() {
      describe('areaAreaIdDelete', function() {
        it('should call areaAreaIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for areaAreaIdDelete call
          /*

          instance.areaAreaIdDelete(areaId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('areaAreaIdGet', function() {
        it('should call areaAreaIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for areaAreaIdGet call and complete the assertions
          /*

          instance.areaAreaIdGet(areaId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Area.Area);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('areaAreaIdPut', function() {
        it('should call areaAreaIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for areaAreaIdPut call
          /*

          instance.areaAreaIdPut(areaId, areaObject, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('areaCreateGet', function() {
        it('should call areaCreateGet successfully', function(done) {
          // TODO: uncomment areaCreateGet call
          /*

          instance.areaCreateGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('areaCreatePost', function() {
        it('should call areaCreatePost successfully', function(done) {
          // TODO: uncomment, update parameter values for areaCreatePost call
          /*
          var opts = {};

          instance.areaCreatePost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAreas', function() {
        it('should call getAreas successfully', function(done) {
          // TODO: uncomment getAreas call and complete the assertions
          /*

          instance.getAreas(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Area.Area);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
