/*
 * AREA
 * Area for epitech
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Area);
  }
}(this, function(expect, Area) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Area.ServicesApi();
  });

  describe('(package)', function() {
    describe('ServicesApi', function() {
      describe('servicesGet', function() {
        it('should call servicesGet successfully', function(done) {
          // TODO: uncomment servicesGet call and complete the assertions
          /*

          instance.servicesGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Area.Service);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('servicesServiceIdActionsGet', function() {
        it('should call servicesServiceIdActionsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for servicesServiceIdActionsGet call and complete the assertions
          /*

          instance.servicesServiceIdActionsGet(serviceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Area.Action);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('servicesServiceIdReactionsGet', function() {
        it('should call servicesServiceIdReactionsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for servicesServiceIdReactionsGet call and complete the assertions
          /*

          instance.servicesServiceIdReactionsGet(serviceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Area.Reaction);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
