version: '3'

services:
  db:
    image: mongo:latest
    container_name: db
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    networks:
      - server-net
    restart: "no"

  server:
    build: "./"
    ports:
      - "8080:8080"
    environment:
      DB_DEBUG: 'mongodb://db:27017/db'
      DB_HOST: 127.0.0.1
      DB_PORT: 27017
      DB_USERNAME: root
      DB_PASSWORD: pass12345
      PORT: 8080
    restart: "no"
    depends_on:
      - db
    links:
      - "db"
    networks:
      - server-net

volumes:
  data:
networks:
  server-net:
    driver: bridge
