/*
 * AREA
 * Area for epitech
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Component} from './Component';

/**
 * The Action model module.
 * @module model/Action
 * @version 1.0.0
 */
export class Action extends Component {
  /**
   * Constructs a new <code>Action</code>.
   * @alias module:model/Action
   * @class
   * @extends module:model/Component
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Action</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Action} obj Optional instance to populate.
   * @return {module:model/Action} The populated <code>Action</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Action();
      Component.constructFromObject(data, obj);
      if (data.hasOwnProperty('serviceId'))
        obj.serviceId = ApiClient.convertToType(data['serviceId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} serviceId
 */
Action.prototype.serviceId = undefined;

