/*
 * AREA
 * Area for epitech
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Action} from './Action';
import {Component} from './Component';
import {Reaction} from './Reaction';

/**
 * The Area model module.
 * @module model/Area
 * @version 1.0.0
 */
export class Area extends Component {
  /**
   * Constructs a new <code>Area</code>.
   * @alias module:model/Area
   * @class
   * @extends module:model/Component
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Area</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Area} obj Optional instance to populate.
   * @return {module:model/Area} The populated <code>Area</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Area();
      Component.constructFromObject(data, obj);
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Boolean');
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], [Action]);
      if (data.hasOwnProperty('reaction'))
        obj.reaction = ApiClient.convertToType(data['reaction'], [Reaction]);
    }
    return obj;
  }
}

/**
 * @member {Boolean} status
 * @default false
 */
Area.prototype.status = false;

/**
 * @member {Array.<module:model/Action>} action
 */
Area.prototype.action = undefined;

/**
 * @member {Array.<module:model/Reaction>} reaction
 */
Area.prototype.reaction = undefined;

