/*
 * AREA
 * Area for epitech
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Component model module.
 * @module model/Component
 * @version 1.0.0
 */
export class Component {
  /**
   * Constructs a new <code>Component</code>.
   * @alias module:model/Component
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Component</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Component} obj Optional instance to populate.
   * @return {module:model/Component} The populated <code>Component</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Component();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Component.prototype.id = undefined;

/**
 * @member {String} name
 */
Component.prototype.name = undefined;

