/*
 * AREA
 * Area for epitech
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Component} from './Component';

/**
 * The Service model module.
 * @module model/Service
 * @version 1.0.0
 */
export class Service extends Component {
  /**
   * Constructs a new <code>Service</code>.
   * @alias module:model/Service
   * @class
   * @extends module:model/Component
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Service</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Service} obj Optional instance to populate.
   * @return {module:model/Service} The populated <code>Service</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Service();
      Component.constructFromObject(data, obj);
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} url
 */
Service.prototype.url = undefined;

