/*
 * AREA
 * Area for epitech
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Area);
  }
}(this, function(expect, Area) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Action', function() {
      beforeEach(function() {
        instance = new Area.Action();
      });

      it('should create an instance of Action', function() {
        // TODO: update the code to test Action
        expect(instance).to.be.a(Area.Action);
      });

      it('should have the property serviceId (base name: "serviceId")', function() {
        // TODO: update the code to test the property serviceId
        expect(instance).to.have.property('serviceId');
        // expect(instance.serviceId).to.be(expectedValueLiteral);
      });

    });
  });

}));
