/*
 * AREA
 * Area for epitech
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Area);
  }
}(this, function(expect, Area) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Area', function() {
      beforeEach(function() {
        instance = new Area.Area();
      });

      it('should create an instance of Area', function() {
        // TODO: update the code to test Area
        expect(instance).to.be.a(Area.Area);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property action (base name: "action")', function() {
        // TODO: update the code to test the property action
        expect(instance).to.have.property('action');
        // expect(instance.action).to.be(expectedValueLiteral);
      });

      it('should have the property reaction (base name: "reaction")', function() {
        // TODO: update the code to test the property reaction
        expect(instance).to.have.property('reaction');
        // expect(instance.reaction).to.be(expectedValueLiteral);
      });

    });
  });

}));
